# GitHub Actions Workflow for Heroku Deployment
# Currently disabled - use Heroku Dashboard GitHub integration instead
# This workflow can be enabled if you prefer CI/CD through GitHub Actions

name: Deploy to Heroku (Disabled)

# Uncomment the 'on' section below if you want to use GitHub Actions
# on:
#   push:
#     branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: false  # This disables the workflow
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        
    - name: Login to Heroku
      run: |
        echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        
    - name: Deploy to Heroku
      run: |
        heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
        git push heroku main
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
